### ISSUE TITLE
rwlock_wrlock assertion fails on Mac OS

### ISSUE THREAD

**Issue by edgar** [appsignal/rdkafka-ruby#33]
I'm using the following `docker-compose.yml` 

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka:1.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.xx.xx.xxx
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "consume_test_topic:3:1,empty_test_topic:3:1,load_test_topic:3:1,produce_test_topic:3:1,rake_test_topic:3:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka:1.0.1
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.xx.xx.xxx
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "consume_test_topic:3:1,empty_test_topic:3:1,load_test_topic:3:1,produce_test_topic:3:1,rake_test_topic:3:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

and then running the specs with `bundle exec rspec` and I'm getting the following error

```
Assertion failed: (r == 0), function rwlock_wrlock, file tinycthread.c, line 1019.
```

The issue is happening in the `spec/rdkafka/consumer_spec.rb`. I'm running MacOS 10.12.6.
